project:
  type: book
  output-dir: docs

book:
  title: "mybook"
  author: "Jane Doe"
  date: "26/05/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - python/intro.qmd
    - part: R/intro.qmd
      chapters:
      - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



